version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-8-boot-2.8.2-node-browsers-legacy
    working_directory: ~/blog
    steps:
      - checkout
      - run: boot build
      - persist_to_workspace:
          root: target
          paths: public

  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email ${GIT_USER_EMAIL}
            git config user.name ${GIT_USER_NAME}
      - add_ssh_keys:
          fingerprints:
            - "ac:6d:13:43:b0:8a:e5:55:f1:e6:30:96:be:25:f3:a3"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --dist target/public \
                     --repo git@github.com:${GIT_DEST} \
                     --branch master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
